remote_theme: "ther0n/minimal-mistakes"
title: "Theron Tjapkes"
name: &name "Theron Tjapkes"
description: ""

plugins:
  - jekyll-feed
  
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : 
  bio              : "Computer science student at Calvin College with interests in information security and game development"
  location         : "Grand Rapids, MI"
  email            : "me@therontjapkes.me"
  uri              : "https://therontjapkes.me"
  home             : "https://therontjapkes.me"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : 
  foursquare       :
  github           : "ther0n"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  jabber           : "aptgetrekt@jabber.org"
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            : "theron1998"
  telegram         : "ther0n_t"
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
